### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by goldbattle** [castacks/tartancalib#1]
Could you please release the datasets used in the paper, or another example dataset to run on?
I don't have access to an extremely wide FOV lense, but would still like to test the code.
Thanks!

**Comment by seeeheng** [comment]
Hi @goldbattle, we plan to release the datasets used within the paper soon. I'll update here once the datasets are up. Thank you for your interest in this.

**Comment by seeeheng** [comment]
We've released the datasets used within the paper in our Wiki. I've added the links here for your convenience, but it'd be best to refer to the wiki in case the links change.

Lensagon Dataset: https://tartancalib.blob.core.windows.net/test-upload/ord-6x6-sep12-500f.bag
GoPro Dataset: https://tartancalib.blob.core.windows.net/test-upload/gopro-6x6-sep12-500f.bag

https://github.com/castacks/tartancalib/wiki/Example:-Calibrating-Single-Camera
https://github.com/castacks/tartancalib/wiki/Example:-Calibrating-Multiple-Cameras

**Comment by XavierQL** [comment]
Maybe something wrong in github. the dataset is missing right now. would you please update the dateaset again? Much appreciated
