### ISSUE TITLE
datasets is missing

### ISSUE THREAD

**Issue by XavierQL** [castacks/tartancalib#14]
Maybe something wrong in github. the datasets is missing right now. would you please update the dateaset again? Much appreciated
https://tartancalib.blob.core.windows.net/test-upload/gopro-6x6-sep12-500f.bag

**Comment by Duisterhof** [comment]
Hi Xavier, we have recently migrated the data from Azure to Google Drive. The new link is [here](https://drive.google.com/drive/folders/1I3MNMHgfdxaaP2HGcTiFAfLouqNoI1I2?usp=sharing), does that work for you?

**Comment by XavierQL** [comment]
much appreciated
